export const CHECK_CONNECTION = "CHECK_CONNECTION";
export const CHECK_CONNECTION_CONNECTED = "CHECK_CONNECTION_CONNECTED";
export const CHECK_CONNECTION_DISCONNECTED = "CHECK_CONNECTION_DISCONNECTED";
